export const RELATED_MAP: Record<string, string[]> = {
  "how-to-read-indian-bank-statement": [
    "understanding-upi-transactions-bank-statement",
    "what-is-neft-rtgs-imps-in-bank-statement",
    "how-to-track-expenses-using-bank-statement",
    "convert-bank-statement-pdf-to-excel",
  ],
  "sbi-bank-statement-download-guide": [
    "how-to-read-sbi-bank-statement",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
    "bank-statement-for-income-tax-return",
  ],
  "hdfc-bank-statement-download": [
    "how-to-read-hdfc-bank-statement-pdf",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
    "bank-statement-password-removal-guide",
  ],
  "icici-bank-statement-download": [
    "how-to-read-icici-bank-statement",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
    "bank-statement-for-income-tax-return",
  ],
  "axis-bank-statement-download": [
    "how-to-read-indian-bank-statement",
    "indian-bank-statement-formats-differences",
    "convert-bank-statement-pdf-to-excel",
    "bank-statement-password-removal-guide",
  ],
  "kotak-bank-statement-download": [
    "kotak-811-account-statement",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
    "bank-statement-password-removal-guide",
  ],
  "bank-statement-for-income-tax-return": [
    "how-to-reconcile-bank-statement",
    "how-to-prepare-bank-statement-for-ca",
    "gst-and-bank-statements-what-businesses-need-to-know",
    "how-to-track-expenses-using-bank-statement",
  ],
  "bank-statement-for-visa-application": [
    "how-to-get-certified-bank-statement",
    "bank-statement-for-home-loan",
    "bank-statement-data-security-best-practices",
    "bank-statement-for-personal-loan",
  ],
  "bank-statement-for-home-loan": [
    "bank-statement-for-personal-loan",
    "bank-statement-for-income-tax-return",
    "how-to-reconcile-bank-statement",
    "bank-statement-for-education-loan",
  ],
  "convert-bank-statement-pdf-to-excel": [
    "how-to-read-indian-bank-statement",
    "how-to-track-expenses-using-bank-statement",
    "how-to-use-bank-statement-api",
    "indian-bank-statement-formats-differences",
  ],
  "understanding-upi-transactions-bank-statement": [
    "what-is-neft-rtgs-imps-in-bank-statement",
    "how-to-spot-fraudulent-transactions-bank-statement",
    "how-to-read-indian-bank-statement",
    "paytm-payments-bank-statement-guide",
  ],
  "bank-statement-analysis-for-accountants": [
    "how-to-reconcile-bank-statement",
    "how-to-prepare-bank-statement-for-ca",
    "gst-and-bank-statements-what-businesses-need-to-know",
    "how-to-use-bank-statement-for-gst-filing",
  ],
  "how-to-reconcile-bank-statement": [
    "understanding-bank-charges-on-statement",
    "how-to-prepare-bank-statement-for-ca",
    "how-to-track-expenses-using-bank-statement",
    "bank-statement-analysis-for-accountants",
  ],
  "understanding-bank-charges-on-statement": [
    "saving-bank-account-vs-current-account-statement",
    "how-to-reconcile-bank-statement",
    "kotak-811-account-statement",
    "small-finance-bank-statement-guide",
  ],
  "punjab-national-bank-statement-download": [
    "sbi-bank-statement-download-guide",
    "canara-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
  ],
  "canara-bank-statement-download": [
    "punjab-national-bank-statement-download",
    "bank-of-baroda-statement-download",
    "how-to-read-indian-bank-statement",
    "convert-bank-statement-pdf-to-excel",
  ],
  "bank-of-baroda-statement-download": [
    "canara-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "how-to-get-certified-bank-statement",
    "convert-bank-statement-pdf-to-excel",
  ],
  "yes-bank-statement-download": [
    "idfc-first-bank-statement-download",
    "indusind-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "bank-statement-password-removal-guide",
  ],
  "idfc-first-bank-statement-download": [
    "yes-bank-statement-download",
    "kotak-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "understanding-bank-charges-on-statement",
  ],
  "indusind-bank-statement-download": [
    "idfc-first-bank-statement-download",
    "federal-bank-statement-download",
    "how-to-get-certified-bank-statement",
    "how-to-read-indian-bank-statement",
  ],
  "federal-bank-statement-download": [
    "nri-bank-account-statement-india",
    "indusind-bank-statement-download",
    "how-to-get-certified-bank-statement",
    "how-to-read-indian-bank-statement",
  ],
  "bank-statement-for-personal-loan": [
    "bank-statement-for-home-loan",
    "how-to-reconcile-bank-statement",
    "how-bank-statements-work-for-freelancers",
    "understanding-emi-entries-bank-statement",
  ],
  "what-is-neft-rtgs-imps-in-bank-statement": [
    "understanding-upi-transactions-bank-statement",
    "how-to-read-indian-bank-statement",
    "how-to-spot-fraudulent-transactions-bank-statement",
    "paytm-payments-bank-statement-guide",
  ],
  "how-to-spot-fraudulent-transactions-bank-statement": [
    "bank-statement-data-security-best-practices",
    "understanding-upi-transactions-bank-statement",
    "bank-statement-password-removal-guide",
    "what-is-neft-rtgs-imps-in-bank-statement",
  ],
  "how-to-track-expenses-using-bank-statement": [
    "how-to-use-bank-statement-for-budgeting",
    "how-to-reconcile-bank-statement",
    "convert-bank-statement-pdf-to-excel",
    "how-to-prepare-bank-statement-for-ca",
  ],
  "gst-and-bank-statements-what-businesses-need-to-know": [
    "how-to-use-bank-statement-for-gst-filing",
    "bank-statement-for-income-tax-return",
    "how-bank-statements-work-for-freelancers",
    "bank-statement-analysis-for-accountants",
  ],
  "how-to-get-certified-bank-statement": [
    "bank-statement-for-visa-application",
    "bank-statement-for-home-loan",
    "bank-statement-data-security-best-practices",
    "bank-statement-for-rent-agreement",
  ],
  "how-to-download-statement-for-all-accounts": [
    "account-aggregator-framework-india",
    "how-to-track-expenses-using-bank-statement",
    "how-to-prepare-bank-statement-for-ca",
    "bank-statement-data-security-best-practices",
  ],
  "account-aggregator-framework-india": [
    "how-to-use-bank-statement-api",
    "future-of-bank-statements-india",
    "bank-statement-data-security-best-practices",
    "how-to-download-statement-for-all-accounts",
  ],
  "bank-statement-for-rent-agreement": [
    "bank-statement-for-home-loan",
    "how-to-get-certified-bank-statement",
    "bank-statement-for-personal-loan",
    "bank-statement-data-security-best-practices",
  ],
  "how-bank-statements-work-for-freelancers": [
    "bank-statement-for-income-tax-return",
    "bank-statement-for-personal-loan",
    "gst-and-bank-statements-what-businesses-need-to-know",
    "how-to-reconcile-bank-statement",
  ],
  "bank-statement-password-removal-guide": [
    "bank-statement-data-security-best-practices",
    "convert-bank-statement-pdf-to-excel",
    "indian-bank-statement-formats-differences",
    "how-to-spot-fraudulent-transactions-bank-statement",
  ],
  "indian-bank-statement-formats-differences": [
    "how-to-read-sbi-bank-statement",
    "how-to-read-hdfc-bank-statement-pdf",
    "how-to-read-icici-bank-statement",
    "convert-bank-statement-pdf-to-excel",
  ],
  "how-to-use-bank-statement-for-budgeting": [
    "how-to-track-expenses-using-bank-statement",
    "how-to-reconcile-bank-statement",
    "how-to-download-statement-for-all-accounts",
    "convert-bank-statement-pdf-to-excel",
  ],
  "nri-bank-account-statement-india": [
    "federal-bank-statement-download",
    "bank-statement-for-income-tax-return",
    "how-to-get-certified-bank-statement",
    "bank-statement-data-security-best-practices",
  ],
  "how-to-read-hdfc-bank-statement-pdf": [
    "hdfc-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "indian-bank-statement-formats-differences",
    "convert-bank-statement-pdf-to-excel",
  ],
  "how-to-read-sbi-bank-statement": [
    "sbi-bank-statement-download-guide",
    "how-to-read-indian-bank-statement",
    "indian-bank-statement-formats-differences",
    "convert-bank-statement-pdf-to-excel",
  ],
  "bank-statement-for-startup-funding": [
    "bank-statement-for-personal-loan",
    "gst-and-bank-statements-what-businesses-need-to-know",
    "how-to-reconcile-bank-statement",
    "bank-statement-analysis-for-accountants",
  ],
  "bank-statement-for-education-loan": [
    "bank-statement-for-personal-loan",
    "bank-statement-for-home-loan",
    "bank-statement-for-income-tax-return",
    "understanding-emi-entries-bank-statement",
  ],
  "saving-bank-account-vs-current-account-statement": [
    "understanding-bank-charges-on-statement",
    "how-to-reconcile-bank-statement",
    "how-to-track-expenses-using-bank-statement",
    "kotak-811-account-statement",
  ],
  "kotak-811-account-statement": [
    "kotak-bank-statement-download",
    "understanding-bank-charges-on-statement",
    "saving-bank-account-vs-current-account-statement",
    "small-finance-bank-statement-guide",
  ],
  "small-finance-bank-statement-guide": [
    "saving-bank-account-vs-current-account-statement",
    "understanding-bank-charges-on-statement",
    "how-to-read-indian-bank-statement",
    "kotak-811-account-statement",
  ],
  "how-to-read-icici-bank-statement": [
    "icici-bank-statement-download",
    "how-to-read-indian-bank-statement",
    "indian-bank-statement-formats-differences",
    "convert-bank-statement-pdf-to-excel",
  ],
  "bank-statement-data-security-best-practices": [
    "bank-statement-password-removal-guide",
    "how-to-get-certified-bank-statement",
    "how-to-spot-fraudulent-transactions-bank-statement",
    "account-aggregator-framework-india",
  ],
  "how-to-use-bank-statement-for-gst-filing": [
    "gst-and-bank-statements-what-businesses-need-to-know",
    "bank-statement-for-income-tax-return",
    "how-to-reconcile-bank-statement",
    "how-to-prepare-bank-statement-for-ca",
  ],
  "paytm-payments-bank-statement-guide": [
    "kotak-811-account-statement",
    "understanding-upi-transactions-bank-statement",
    "what-is-neft-rtgs-imps-in-bank-statement",
    "how-to-spot-fraudulent-transactions-bank-statement",
  ],
  "understanding-emi-entries-bank-statement": [
    "bank-statement-for-personal-loan",
    "bank-statement-for-home-loan",
    "how-to-reconcile-bank-statement",
    "bank-statement-for-education-loan",
  ],
  "how-to-use-bank-statement-api": [
    "account-aggregator-framework-india",
    "convert-bank-statement-pdf-to-excel",
    "future-of-bank-statements-india",
    "indian-bank-statement-formats-differences",
  ],
  "how-to-prepare-bank-statement-for-ca": [
    "bank-statement-for-income-tax-return",
    "how-to-use-bank-statement-for-gst-filing",
    "convert-bank-statement-pdf-to-excel",
    "how-to-reconcile-bank-statement",
  ],
  "future-of-bank-statements-india": [
    "account-aggregator-framework-india",
    "how-to-use-bank-statement-api",
    "bank-statement-data-security-best-practices",
    "how-to-download-statement-for-all-accounts",
  ],
};
