/**
 * Canonical global bank name list — single source of truth.
 * Used by process-statement, bulk-process, and the Python backend.
 *
 * Each entry: [keyword (lowercase), canonical display name]
 * Keywords are tested in order; first match wins.
 */
export const SUPPORTED_BANKS: [string, string][] = [
  // US Banks
  ["jpmorgan chase", "JPMorgan Chase"],
  ["chase bank", "JPMorgan Chase"],
  ["chase", "JPMorgan Chase"],
  ["bank of america", "Bank of America"],
  ["bofa", "Bank of America"],
  ["wells fargo", "Wells Fargo"],
  ["citibank", "Citibank"],
  ["citi", "Citibank"],
  ["us bank", "U.S. Bank"],
  ["u.s. bank", "U.S. Bank"],
  ["pnc bank", "PNC Bank"],
  ["pnc", "PNC Bank"],
  ["truist", "Truist"],
  ["capital one", "Capital One"],
  ["td bank", "TD Bank"],

  // UK Banks
  ["hsbc", "HSBC"],
  ["barclays", "Barclays"],
  ["lloyds", "Lloyds Bank"],
  ["natwest", "NatWest"],
  ["standard chartered", "Standard Chartered"],
  ["royal bank of scotland", "Royal Bank of Scotland"],
  ["rbs", "Royal Bank of Scotland"],
  ["santander uk", "Santander UK"],
  ["nationwide building society", "Nationwide"],
  ["nationwide", "Nationwide"],
  ["halifax", "Halifax"],

  // Canada Banks
  ["royal bank of canada", "Royal Bank of Canada (RBC)"],
  ["rbc", "Royal Bank of Canada (RBC)"],
  ["toronto-dominion", "TD Bank (Canada)"],
  ["scotiabank", "Scotiabank"],
  ["bank of nova scotia", "Scotiabank"],
  ["bank of montreal", "BMO"],
  ["bmo", "BMO"],
  ["canadian imperial bank of commerce", "CIBC"],
  ["cibc", "CIBC"],

  // Australia Banks
  ["commonwealth bank", "Commonwealth Bank (CBA)"],
  ["cba", "Commonwealth Bank (CBA)"],
  ["westpac", "Westpac"],
  ["anz", "ANZ"],
  ["nab", "National Australia Bank (NAB)"],
  ["national australia bank", "National Australia Bank (NAB)"],
  ["macquarie", "Macquarie Bank"],

  // European Banks
  ["bnp paribas", "BNP Paribas"],
  ["credit agricole", "Crédit Agricole"],
  ["societe generale", "Société Générale"],
  ["deutsche bank", "Deutsche Bank"],
  ["commerzbank", "Commerzbank"],
  ["santander", "Banco Santander"],
  ["bbva", "BBVA"],
  ["ing", "ING Bank"],
  ["rabobank", "Rabobank"],
  ["ubs", "UBS"],
  ["credit suisse", "Credit Suisse"],
  ["unicredit", "UniCredit"],
  ["intesasanpaolo", "Intesa Sanpaolo"],

  // Indian Banks
  ["state bank of india", "State Bank of India (SBI)"],
  ["state bank",          "State Bank of India (SBI)"],
  ["sbi",                 "State Bank of India (SBI)"],
  ["hdfc",                "HDFC Bank"],
  ["icici",               "ICICI Bank"],
  ["axis bank",           "Axis Bank"],
  ["axis",                "Axis Bank"],
  ["kotak mahindra",      "Kotak Mahindra Bank"],
  ["kotak",               "Kotak Mahindra Bank"],
  ["punjab national bank","Punjab National Bank"],
  ["pnb",                 "Punjab National Bank"],
  ["bank of baroda",      "Bank of Baroda"],
  ["bob",                 "Bank of Baroda"],
  ["canara bank",         "Canara Bank"],
  ["canara",              "Canara Bank"],
  ["union bank of india", "Union Bank of India"],
  ["union bank",          "Union Bank of India"],
  ["bank of india",       "Bank of India"],
  ["central bank of india","Central Bank of India"],
  ["central bank",        "Central Bank of India"],
  ["indian bank",         "Indian Bank"],
  ["uco bank",            "UCO Bank"],
  ["indusind",            "IndusInd Bank"],
  ["yes bank",            "Yes Bank"],
  ["idfc first",          "IDFC FIRST Bank"],
  ["idfc",                "IDFC FIRST Bank"],
  ["federal bank",        "Federal Bank"],
  ["south indian bank",   "South Indian Bank"],
  ["rbl bank",            "RBL Bank"],
  ["rbl",                 "RBL Bank"],
  ["bandhan",             "Bandhan Bank"],
  ["au small finance",    "AU Small Finance Bank"],
  ["au bank",             "AU Small Finance Bank"],
  ["paytm payments bank", "Paytm Payments Bank"],
  ["paytm",               "Paytm Payments Bank"],
  ["airtel payments bank","Airtel Payments Bank"],
  ["airtel",              "Airtel Payments Bank"],
  // Added from bankstatementwizard.com
  ["1 first bank", "1 First Bank"],
  ["abhyudaya co-op. bank ltd.", "Abhyudaya Co-op. Bank Ltd."],
  ["abk", "ABK"],
  ["abn amro bank", "ABN AMRO Bank"],
  ["absa", "Absa"],
  ["abu dhabi commercial bank", "Abu Dhabi Commercial Bank"],
  ["abu dhabi islamic bank", "Abu Dhabi Islamic Bank"],
  ["adc bank", "ADC Bank"],
  ["agribank", "AgriBank"],
  ["ahli united bank of kuwait", "Ahli United Bank of Kuwait"],
  ["ajman bank", "Ajman Bank"],
  ["akbank", "AKBank"],
  ["akola janata bank", "Akola Janata Bank"],
  ["aladin", "Aladin"],
  ["alat", "ALAT"],
  ["albaraka bank", "alBaraka Bank"],
  ["alfa bank", "Alfa Bank"],
  ["alliance bank", "Alliance Bank"],
  ["allied irish banks", "Allied Irish Banks"],
  ["al rajhi bank saudi arabia", "Al Rajhi Bank Saudi Arabia"],
  ["alterna savings", "Alterna Savings"],
  ["amazon synchrony", "Amazon Synchrony"],
  ["ambank", "AmBank"],
  ["amegy bank of texas", "Amegy Bank of Texas"],
  ["amex", "AMEX"],
  ["amex card australia", "AMEX Card Australia"],
  ["amex card canada", "AMEX Card Canada"],
  ["amex card france", "AMEX Card France"],
  ["amex card uk", "AMEX Card UK"],
  ["amex (middle east)", "AMEX (Middle East)"],
  ["anna", "ANNA"],
  ["apple card", "Apple Card"],
  ["arnagar bank", "Arnagar Bank"],
  ["ascend federal credit union", "Ascend Federal Credit Union"],
  ["asda money", "Asda Money"],
  ["asia commercial bank", "Asia Commercial Bank"],
  ["atlantic union bank", "Atlantic Union Bank"],
  ["attijariwafa bank", "Attijariwafa Bank"],
  ["axess", "Axess"],
  ["banamex", "Banamex"],
  ["banca monte dei paschi di siena", "Banca Monte dei Paschi di Siena"],
  ["bancfirst", "BancFirst"],
  ["banco av villas", "Banco AV Villas"],
  ["banco bpm", "Banco BPM"],
  ["banco bradesco", "Banco Bradesco"],
  ["banco de corrientes", "Banco de Corrientes"],
  ["banco de crédito del perú", "Banco de Crédito del Perú"],
  ["banco de galicia", "Banco de Galicia"],
  ["banco de la nacion argentina", "Banco de la Nacion Argentina"],
  ["bancolombia", "Bancolombia"],
  ["banco patagonia", "Banco Patagonia"],
  ["banco português de investimento", "Banco Português de Investimento"],
  ["bancor", "Bancor"],
  ["banistmo", "Banistmo"],
  ["bank alfalah", "Bank Alfalah"],
  ["bank al habib", "Bank AL Habib"],
  ["bank central asia", "Bank Central Asia"],
  ["bank gaborone", "Bank Gaborone"],
  ["bank mandiri", "Bank Mandiri"],
  ["bank mega", "Bank Mega"],
  ["bank neo commerce", "Bank Neo Commerce"],
  ["bank of bahrain and kuwait", "Bank of Bahrain and Kuwait"],
  ["bank of china (hong kong)", "Bank of China (Hong Kong)"],
  ["bank of cyprus", "Bank Of Cyprus"],
  ["bank of hope", "Bank of Hope"],
  ["bank of ireland", "Bank of Ireland"],
  ["bank of kigali", "Bank of Kigali"],
  ["bank of maharashtra", "Bank of Maharashtra"],
  ["bank of melbourne", "Bank of Melbourne"],
  ["bank of new zealand", "Bank of New Zealand"],
  ["bank of scotland", "Bank of Scotland"],
  ["bank of the west", "Bank of the West"],
  ["bank of travelers rest", "Bank of Travelers Rest"],
  ["bank pekao", "Bank Pekao"],
  ["bank polski", "Bank Polski"],
  ["banksa", "BankSA"],
  ["bank sinarmas", "Bank Sinarmas"],
  ["bank windhoek", "Bank Windhoek"],
  ["banner bank", "Banner Bank"],
  ["banorte", "Banorte"],
  ["banque cic", "Banque CIC"],
  ["banque laurentienne", "Banque Laurentienne"],
  ["banque populaire", "Banque Populaire"],
  ["banque populaire doujda", "Banque Populaire Doujda"],
  ["b bank", "B Bank"],
  ["benchmark community bank", "Benchmark Community Bank"],
  ["beobank", "BeoBank"],
  ["bergische volksbank", "Bergische Volksbank"],
  ["berliner sparkasse", "Berliner Sparkasse"],
  ["bgfibank europe", "BGFIBank Europe"],
  ["bgl bnp paribas", "BGL BNP PARIBAS"],
  ["bharat bank", "Bharat Bank"],
  ["bicholim urban co-operative bank", "Bicholim Urban Co-operative Bank"],
  ["bilt rewards", "Bilt Rewards"],
  ["bluevine", "Bluevine"],
  ["bni", "BNI"],
  ["bourso bank", "Bourso Bank"],
  ["bred banque populaire", "BRED Banque Populaire"],
  ["brubank", "Brubank"],
  ["bsp financial group", "BSP Financial Group"],
  ["bsp financial group limited", "BSP Financial Group Limited"],
  ["bunq", "Bunq"],
  ["cadence bank", "Cadence Bank"],
  ["caisse d'epargne", "Caisse d'Epargne"],
  ["caisse d’epargne", "Caisse d’Epargne"],
  ["caisse d'epargne et de prévoyance de midi-pyrénées", "Caisse d'Epargne et de Prévoyance de Midi-Pyrénées"],
  ["caixabank", "CaixaBank"],
  ["caixa geral de depósitos", "Caixa Geral de Depósitos"],
  ["calprivate bank", "CalPrivate Bank"],
  ["canvas credit union", "Canvas Credit Union"],
  ["capitalone", "CapitalOne"],
  ["capitalontap", "CapitalOnTap"],
  ["capitec bank", "Capitec Bank"],
  ["card one money", "Card One Money"],
  ["cargills bank", "Cargills Bank"],
  ["carolina bank", "Carolina Bank"],
  ["cash app", "Cash App"],
  ["cashplus bank", "Cashplus Bank"],
  ["ccf", "CCF"],
  ["centennial bank", "Centennial Bank"],
  ["československá obchodní banka", "Československá obchodní banka"],
  ["chase southwest", "Chase Southwest"],
  ["chime", "Chime"],
  ["cimb bank", "CIMB BANK"],
  ["cimb niaga", "CIMB Niaga"],
  ["citi cards", "Citi Cards"],
  ["citi handlowy", "Citi Handlowy"],
  ["citizens bank", "Citizens Bank"],
  ["city national bank", "City National Bank"],
  ["city union bank", "City Union Bank"],
  ["ckb banka", "CKB Banka"],
  ["clientis", "Clientis"],
  ["columbia credit union", "Columbia Credit Union"],
  ["comdirect", "Comdirect"],
  ["commerical bank of dubai", "Commerical Bank of Dubai"],
  ["commonwealth bank of australia", "Commonwealth Bank of Australia"],
  ["community bank of louisiana", "Community Bank of Louisiana"],
  ["connect first credit union", "Connect First Credit Union"],
  ["consors bank", "Consors Bank"],
  ["cosmos co-operative bank ltd", "Cosmos Co-operative Bank Ltd"],
  ["costco anywhere visa card by citi", "Costco Anywhere Visa Card by Citi"],
  ["crate and barrel credit card", "Crate And Barrel Credit Card"],
  ["crdb bank", "CRDB Bank"],
  ["credins bank", "Credins Bank"],
  ["crédit industriel et commercial", "Crédit Industriel et Commercial"],
  ["credit karma", "Credit Karma"],
  ["credit mutel", "Credit Mutel"],
  ["credito agricola", "Credito Agricola"],
  ["credit one bank", "Credit One Bank"],
  ["csb bank", "CSB Bank"],
  ["danamon bank", "Danamon Bank"],
  ["danske bank", "Danske Bank"],
  ["dbs", "DBS"],
  ["dcb bank", "DCB Bank"],
  ["desjardins", "Desjardins"],
  ["deutsche kreditbank", "Deutsche Kreditbank"],
  ["dhanlaxmi bank", "Dhanlaxmi Bank"],
  ["discover card", "Discover Card"],
  ["dnb asa", "DNB ASA"],
  ["dod community bank", "DOD Community Bank"],
  ["dollar bank", "Dollar Bank"],
  ["dubai islamic bank", "Dubai Islamic Bank"],
  ["dutch bangla bank", "Dutch Bangla Bank"],
  ["eagle bank", "Eagle Bank"],
  ["easybank", "EasyBank"],
  ["efirstbank", "EFirstBank"],
  ["emirates islamic bank", "Emirates Islamic Bank"],
  ["emirates nbd", "Emirates NBD"],
  ["ent credit union", "Ent Credit Union"],
  ["eposnow", "EposNow"],
  ["equitas small finance bank", "Equitas Small Finance Bank"],
  ["equity bank kenya", "Equity Bank Kenya"],
  ["esaf small finance bank", "ESAF Small Finance Bank"],
  ["faysal bank", "Faysal Bank"],
  ["federal bank india", "Federal Bank India"],
  ["fidelity", "Fidelity"],
  ["fifth third", "Fifth Third"],
  ["fifth third private bank", "Fifth Third Private Bank"],
  ["finacle", "Finacle"],
  ["first abu dhabi bank", "First Abu Dhabi Bank"],
  ["first bancorp", "First BanCorp"],
  ["first citizens bank", "First Citizens Bank"],
  ["first city monument bank", "First City Monument Bank"],
  ["first direct", "First Direct"],
  ["first horizon", "First Horizon"],
  ["first national bank namibia", "First National Bank Namibia"],
  ["first national bank of botswana", "First National Bank of Botswana"],
  ["first national bank of lesotho", "First National Bank of Lesotho"],
  ["first national bank south africa", "First National Bank South Africa"],
  ["first national bank zambia", "First National Bank Zambia"],
  ["first state bank", "First State Bank"],
  ["first united", "First United"],
  ["fortuneo", "Fortuneo"],
  ["freiburger kantonalbank", "Freiburger Kantonalbank"],
  ["galicia mas", "Galicia Mas"],
  ["gem finance", "GEM Finance"],
  ["glacier bank", "Glacier Bank"],
  ["gls gemeinschaftsbank", "GLS Gemeinschaftsbank"],
  ["guaranty trust bank", "Guaranty Trust Bank"],
  ["habib bank ag zurich", "Habib Bank AG Zurich"],
  ["habib metropolitan bank ltd", "Habib Metropolitan Bank Ltd"],
  ["hang seng bank", "Hang Seng Bank"],
  ["hatton national bank", "Hatton National Bank"],
  ["hbl", "HBL"],
  ["hongleong bank", "HongLeong Bank"],
  ["hsbc amanah", "HSBC Amanah"],
  ["hsbc mastercard", "HSBC Mastercard"],
  ["hsbc uk", "HSBC UK"],
  ["huntington bank", "Huntington Bank"],
  ["ibc bank", "IBC Bank"],
  ["idb bank", "IDB Bank"],
  ["idbi bank", "IDBI Bank"],
  ["illinois bank \u0026 trust", "Illinois Bank \u0026 Trust"],
  ["im bank", "IM Bank"],
  ["inbursa financiero", "Inbursa Financiero"],
  ["indian overseas bank", "Indian Overseas Bank"],
  ["indo zambian bank", "Indo Zambian Bank"],
  ["induslnd bank", "Induslnd Bank"],
  ["infinitepay", "InfinitePay"],
  ["interaudi bank", "Interaudi Bank"],
  ["international card services", "International Card Services"],
  ["international finance bank", "International Finance Bank"],
  ["investec bank", "Investec Bank"],
  ["island savings", "Island Savings"],
  ["itaú unibanco", "Itaú Unibanco"],
  ["jammu and kashmir bank", "Jammu and Kashmir Bank"],
  ["jana small finance bank", "Jana Small Finance Bank"],
  ["janata sahakari bank", "Janata Sahakari Bank"],
  ["jazzcash", "JazzCash"],
  ["jio payments bank", "Jio Payments Bank"],
  ["karnatka bank", "Karnatka Bank"],
  ["karur vysya bank", "Karur Vysya Bank"],
  ["kasikornbank", "Kasikornbank"],
  ["kcb bank", "KCB Bank"],
  ["koinx", "KoinX"],
  ["kreissparkasse ostalb", "Kreissparkasse Ostalb"],
  ["kreissparkasse steinfurt", "Kreissparkasse Steinfurt"],
  ["la banque postale", "La Banque Postale"],
  ["lake trust", "Lake Trust"],
  ["le credit lyonnais", "Le Credit Lyonnais"],
  ["lesotho postbank", "Lesotho PostBank"],
  ["lgfcu north carolina", "LGFCU North Carolina"],
  ["libro credit union", "Libro Credit Union"],
  ["lunar", "Lunar"],
  ["macro bank", "Macro Bank"],
  ["maharashtra gramin bank", "Maharashtra Gramin Bank"],
  ["mashreq bank", "Mashreq Bank"],
  ["mauritius commercial bank ", "Mauritius Commercial Bank "],
  ["maybank", "Maybank"],
  ["mbank", "mBank"],
  ["mbna", "MBNA"],
  ["mcb islamic", "MCB Islamic"],
  ["mct credit union", "MCT Credit Union"],
  ["meezan bank", "Meezan Bank"],
  ["member first credit union", "Member First Credit Union"],
  ["merchants bank", "Merchants Bank"],
  ["mercury bank", "Mercury Bank"],
  ["meridian cu canada", "Meridian CU Canada"],
  ["meta", "Meta"],
  ["metro bank", "Metro Bank"],
  ["mettle", "Mettle"],
  ["mission lane", "Mission Lane"],
  ["monarch networth capital", "Monarch Networth Capital"],
  ["monzo", "Monzo"],
  ["mountain america credit union", "Mountain America Credit Union"],
  ["mox bank", "MOX Bank"],
  ["mufg bank", "MUFG Bank"],
  ["municipal co-operative bank", "Municipal Co-Operative Bank"],
  ["n26", "N26"],
  ["national bank of canada", "National Bank of Canada"],
  ["national bank of pakistan", "National Bank of Pakistan"],
  ["national commercial bank jamaica", "National Commercial Bank Jamaica"],
  ["national westminster bank", "National Westminster Bank"],
  ["ncba bank kenya", "NCBA Bank Kenya"],
  ["ncb jamaica", "NCB Jamaica"],
  ["ndb bank", "NDB Bank"],
  ["nedbank", "Nedbank"],
  ["nedbank lesotho", "Nedbank Lesotho"],
  ["netspend", "Netspend"],
  ["niederrheinische sparkasse", "Niederrheinische Sparkasse"],
  ["niyo", "Niyo"],
  ["nmb bank tanzania", "NMB Bank Tanzania"],
  ["norisbank", "Norisbank"],
  ["northpointe bank", "Northpointe Bank"],
  ["novo banco", "Novo Banco"],
  ["nrbc bank", "NRBC Bank"],
  ["nubank", "Nubank"],
  ["ocbc bank", "OCBC Bank"],
  ["ocean bank", "Ocean Bank"],
  ["oriental bank", "Oriental Bank"],
  ["pagbank", "PagBank"],
  ["paycenter", "PayCenter"],
  ["paypal", "PayPal"],
  ["pcb bank", "PCB Bank"],
  ["pelican credit state union", "Pelican Credit State Union"],
  ["penfed", "PenFed"],
  ["penta by qonto", "Penta by Qonto"],
  ["peppermoney", "Peppermoney"],
  ["permanent tsb", "Permanent TSB"],
  ["phonepe", "PhonePe"],
  ["pinnacle financial partners", "Pinnacle Financial Partners"],
  ["piramal finance", "Piramal Finance"],
  ["popular bank", "Popular Bank"],
  ["posbank", "POSBank"],
  ["postbank", "Postbank"],
  ["postfinance", "PostFinance"],
  ["presidents choice financial", "Presidents Choice Financial"],
  ["prime bank", "Prime Bank"],
  ["prime co operative bank", "Prime Co Operative Bank"],
  ["primis bank", "Primis Bank"],
  ["prosperity bank", "Prosperity Bank"],
  ["psd bank", "PSD Bank"],
  ["public bank berhad", "Public Bank Berhad"],
  ["punjab and sind bank", "Punjab and Sind Bank"],
  ["qonto", "Qonto"],
  ["raiffeisenbank ch", "Raiffeisenbank CH"],
  ["raiffeisen bank serbia", "Raiffeisen Bank Serbia"],
  ["raiffeisen ch", "Raiffeisen CH"],
  ["rakbank", "RAKBank"],
  ["rave financial", "Rave Financial"],
  ["rbc royal bank of canada", "RBC Royal Bank Of Canada"],
  ["rcbc credit", "RCBC Credit"],
  ["redstone bank", "Redstone Bank"],
  ["redstone federal credit union", "Redstone Federal Credit Union"],
  ["red wing credit union", "Red Wing Credit Union"],
  ["redwood credit union", "Redwood Credit Union"],
  ["regent bank", "Regent Bank"],
  ["regions bank", "Regions Bank"],
  ["revolut", "Revolut"],
  ["rhb", "RHB"],
  ["riyad bank", "Riyad Bank"],
  ["rmb private bank", "RMB Private Bank"],
  ["sacombank", "Sacombank"],
  ["safra national bank", "Safra National Bank"],
  ["sagicor bank jamaica", "Sagicor Bank Jamaica"],
  ["samarth sahkari bank", "Samarth Sahkari Bank"],
  ["saraswat bank", "Saraswat Bank"],
  ["saudi national bank", "Saudi National Bank"],
  ["sberbank", "Sberbank"],
  ["scapia cards", "Scapia Cards"],
  ["seb", "SEB"],
  ["security service federal credit union", "Security Service Federal Credit Union"],
  ["servus credit union", "Servus Credit Union"],
  ["sf fire credit union", "SF Fire Credit Union"],
  ["sharjah islamic bank", "Sharjah Islamic Bank"],
  ["shinhan bank", "Shinhan Bank"],
  ["silicon valley bank", "Silicon Valley Bank"],
  ["simplii financial", "Simplii Financial"],
  ["sindhudurg", "Sindhudurg"],
  ["sns bank", "SNS Bank"],
  ["social finance", "Social Finance"],
  ["sogexia", "Sogexia"],
  ["sohar international bank", "Sohar International Bank"],
  ["soneri bank", "Soneri Bank"],
  ["sovereign international", "Sovereign International"],
  ["sparda bank", "Sparda Bank"],
  ["sparkasse hanau", "Sparkasse Hanau"],
  ["sparkasse kölnbonn", "Sparkasse KölnBonn"],
  ["sparkasse paderborn-detmold", "Sparkasse Paderborn-Detmold"],
  ["sparkasse schwyz ag", "Sparkasse Schwyz AG"],
  ["square", "Square"],
  ["stanbic bank kenya", "Stanbic Bank Kenya"],
  ["standard bank of south africa", "Standard Bank of South Africa"],
  ["standard lesotho bank", "Standard Lesotho Bank"],
  ["starling bank", "Starling Bank"],
  ["state employees credit union", "State Employees Credit Union"],
  ["st bank", "ST Bank"],
  ["st. george bank", "St. George Bank"],
  ["suncorp", "Suncorp"],
  ["suntrust bank", "SunTrust Bank"],
  ["surat people cooperative bank", "Surat People Cooperative Bank"],
  ["suvrnayug sahakari bank", "Suvrnayug Sahakari Bank"],
  ["svc bank", "SVC Bank"],
  ["swedbank", "Swedbank"],
  ["tamilnad mercantile bank", "Tamilnad Mercantile Bank"],
  ["tangerine bank", "Tangerine Bank"],
  ["texas capital bank", "Texas Capital Bank"],
  ["thane bharat sahakari bank ltd.", "Thane Bharat Sahakari Bank Ltd."],
  ["the co-operative bank", "The Co-operative Bank"],
  ["the frederick community bank", "The Frederick Community Bank"],
  ["the muslim co-operative bank", "The Muslim Co-Operative Bank"],
  ["the peoples bank la", "The Peoples Bank LA"],
  ["tide", "Tide"],
  ["tjsb bank", "TJSB Bank"],
  ["trade republic", "Trade Republic"],
  ["truliant", "Truliant"],
  ["trust bank singapore", "Trust Bank Singapore"],
  ["tsb bank", "TSB Bank"],
  ["türkiye bankasi", "Türkiye Bankasi"],
  ["txn", "TXN"],
  ["ubl united bank limited", "UBL United Bank Limited"],
  ["ueno bank", "Ueno Bank"],
  ["ulster bank", "Ulster Bank"],
  ["uncle credit union", "Uncle Credit Union"],
  ["unionbank of the philippines", "UnionBank of the Philippines"],
  ["united overseas bank", "United Overseas Bank"],
  ["usaa", "USAA"],
  ["vailant", "Vailant"],
  ["vancity", "Vancity"],
  ["venmo", "Venmo"],
  ["verizon", "Verizon"],
  ["viainvest", "VIAInvest"],
  ["vietcombank", "Vietcombank"],
  ["vietinbank", "VietinBank"],
  ["virginia national bank", "Virginia National Bank"],
  ["virgin money", "Virgin Money"],
  ["volksbank deutschland", "Volksbank Deutschland"],
  ["volksbank prina", "Volksbank Prina"],
  ["volunteer state bank", "Volunteer State Bank"],
  ["vtb bank", "VTB Bank"],
  ["vystar credit union", "VyStar Credit Union"],
  ["wallis bank", "Wallis Bank"],
  ["webster bank", "Webster Bank"],
  ["wesbanco", "WesBanco"],
  ["wio bank", "WIO Bank"],
  ["wise", "Wise"],
  ["woori america bank", "Woori America Bank"],
  ["wsecu", "WSECU"],
  ["yapi kredi", "Yapi Kredi"],
  ["zempler bank", "Zempler Bank"],
  ["zenith bank", "Zenith Bank"],
  ["zento", "Zento"],
  ["zipmoney", "ZipMoney"],
  ["ziraat bankas", "Ziraat Bankas"],
];

/**
 * Infer the canonical bank name from a filename and/or PDF text snippet.
 * Returns null if no known bank is detected.
 */
export function inferBankName(filename: string, pdfTextSnippet = ""): string | null {
  const haystack = (filename + " " + pdfTextSnippet).toLowerCase();
  for (const [keyword, name] of SUPPORTED_BANKS) {
    if (haystack.includes(keyword)) return name;
  }
  return null;
}
